### ISSUE TITLE
docker-compose post edits

### ISSUE THREAD

**Issue by ojha-url** [UrbanRiskSlumRedevelopment/Hermes#1]
Despite running `docker-compose down --volumes`, edits made in package.json not picked up? (node app name still shows risk-map-server instead of housing-app-server)

**Comment by ojha-url** [comment]
ok, have to manually remove previous images & recreate them. Write master deploy script?

**Comment by abrahamq** [comment]
You don't have to remove, you have do have to remake them. ./makeImage.sh . docker-compose is just picking up on the image names you gave them when you created them.
